server:
  port: 8888
  context-path: /
#  jsp-servlet
#    init-parameters:
#      development: true

logging:
  level: info
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://106.75.168.129:3306/cash_book?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
#    password: F7wkOiVTassfoUPxXBMS+r56ZJfAfDt7bivphK+ZwqhM+V3TV7YJYbN6Fxp+bQOEGdRntEm2q7eqZLZse+AUdg==
    password: xu@18823748161
    filters: config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;config.decrypt=true;config.decrypt.key=${publickey}
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  mvc:
    static-path-pattern: /static/**
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: xukefu_vip@163.com
    password: BLIBOOJZSWKQXUOO
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.xkf.cashbook.web.mapper
  mapper-locations: classpath*:mapper/*.xml

mail:
  fromMail:
    addr: xukefu_vip@163.com

publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANJB/MUeQRTFn1FT1ILWuZGraAjbnZjLHC9DhmD0IQq05zSVAdQznitFgNYBE3Ug5aeNw9p6chf28CA+6RsUsRECAwEAAQ==