server:
  port: 80
  context-path: /

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-wz934k87p3x05053noo.mysql.rds.aliyuncs.com/cash_book?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: xukefu
    password: xu@18823748161
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  mvc:
    static-path-pattern: /static/**
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: xukefu_vip@163.com
    password: BLIBOOJZSWKQXUOO
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.xkf.cashbook.mysql.mapper
  mapper-locations: classpath*:mapper/*.xml

mail:
  fromMail:
    addr: xukefu_vip@163.com

publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANJB/MUeQRTFn1FT1ILWuZGraAjbnZjLHC9DhmD0IQq05zSVAdQznitFgNYBE3Ug5aeNw9p6chf28CA+6RsUsRECAwEAAQ==


